Repository ucsb-cs156-f23/proj-happycows-f23-5pm-2, pull requests merged in 2023-11, with the labels that each got.

#26 Dollar Sign Added and Right Justified
  frontend/src/main/components/OurTable.js
  frontend/src/main/components/Reports/ReportHeaderTable.js
  frontend/src/main/components/Reports/ReportLineTable.js
  frontend/src/tests/components/OurTable.test.js
  frontend/src/tests/components/Reports/ReportHeaderTable.test.js
  frontend/src/tests/components/Reports/ReportLineTable.test.js
  src/main/java/edu/ucsb/cs156/happiercows/entities/Report.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/ReportLine.java
Labels: 10

#22 Added tooltips for all parts of the Create Commons Form except for ending date, as of this commit ending date does not yet exist
  frontend/src/main/components/Commons/CommonsForm.js
Labels: 5, Merge Candidate

#31 Hancheng default commons UI
  frontend/src/main/components/Commons/CommonsList.js
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/tests/components/Commons/CommonsList.test.js
Labels: 10, Merge Candidate

#25 Updated the leaderboard and added tests
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
  frontend/src/tests/pages/LeaderboardPage.test.js
Labels: FIXME-see code review

#36 Chinmay - refactor chattoggle from PlayPage.js into it's own React Component
  frontend/src/main/components/Chat/ChatToggle.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/stories/components/Chat/ChatToggle.stories.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: 10

#39 Changed commons form to use default values from /defaults endpoint instead of hard coded values
  README.md
  docs/environment.md
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
Labels: 10

#37 Implemented gameInProgress() under Commons entity, and tests
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/CommonsTests.java
Labels: 10, Merge Candidate

#41 Created entity and repository files for Announcement
  src/main/java/edu/ucsb/cs156/happiercows/entities/Announcement.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/AnnouncementRepository.java
Labels: 5, Merge Candidate

#46 Specified what file changes take priority for default values
  docs/environment.md
Labels: 5, Merge Candidate

#47 Hancheng sorting
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
Labels: 10, Merge Candidate
